### ISSUE TITLE
Iniciar estrutura de pastas

### ISSUE THREAD

**Issue by marcosroriz** [marcosroriz/sete-web#1]
Esta feature tem com objetivo definir a estrutura de pastas do projeto.

**Comment by irwinarruda** [comment]
Certo! Começarei com a feature hoje na parte da noite

**Comment by marcosroriz** [comment]
Ok, @irwinarruda  👍

**Comment by irwinarruda** [comment]
Boa noite, Professor.
✅ Feature feita em `feature/estrutura-pastas`

**Comment by marcosroriz** [comment]
Ok! Closed.
